apiVersion: v1
kind: ConfigMap
metadata:
    name: coredns
    namespace: dns
data:
    Corefile: |
        url:53 {
            hosts {
                192.168.2.9 megu.url
                192.168.2.9 api.megu.url
                fallthrough
            }
        }

        .:53 {
            forward . 1.1.1.1 8.8.8.8
            cache 30
            errors
        }
