apiVersion: v1
kind: Service
metadata:
    name: coredns
    namespace: dns
spec:
    type: NodePort
    selector:
        app: coredns
    ports:
        - name: dns-udp
          port: 53
          targetPort: 53
          nodePort: 30553
          protocol: UDP

        - name: dns-tcp
          port: 53
          targetPort: 53
          nodePort: 30553
          protocol: TCP
