ca:
    bootstrapIssuer:
        kind: Issuer
        name: local-selfsigned
    certificate:
        name: local-ca
        commonName: Local CA Certificate
        secretName: local-ca-secret

testService:
    type: ClusterIP
    port: 80
