apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
type: Opaque
stringData:
    DATABASE_USER: postgres
    DATABASE_PASSWORD: CHANGE_ME
    DATABASE_HOST: db-service
    DATABASE_PORT: "5432"
    DATABASE_NAME: meguURL
