apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2026-08-16T23:09:32Z"
    name: meguurl-db-api
    namespace: default
    resourceVersion: "4382"
    uid: 45e09384-87c3-4d19-8007-80f7b8e26250
type: Opaque
