services:
    backend:
        image: tomcheese/meguurl-backend-repo:latest
        container_name: meguURL-backend
        environment:
            - ApiSettings__BackendApi=http://backend:8080/
            - ApiSettings__DatabaseApi=http://api:8000/
        ports:
            - "6767:8080"
        volumes:
            - dataprotection-keys:/keys
        networks:
            - megu-network
volumes:
    dataprotection-keys:

networks:
    megu-network:
