services:
    backend:
        image: tomcheese/meguurl-backend-repo:latest
        container_name: meguURL-backend
        env_file:
            - .env.production
        ports:
            - "6767:8080"
        volumes:
            - dataprotection-keys:/keys
        networks:
            - megu-network
volumes:
    dataprotection-keys:

networks:
    megu-network:
