apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: meguurl-local-ca
spec:
    isCA: true
    commonName: meguurl Local CA
    secretName: meguurl-local-ca
    issuerRef:
        name: meguurl-local
        kind: Issuer
