apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: meguurl-local-tls
    namespace: cert-manager
spec:
    secretName: meguurl-local-tls
    dnsNames:
        - meguurl.local
        - api.meguurl.local
    issuerRef:
        name: meguurl-local
        kind: Issuer
