imagePullPolicy: Always

replicaCount: 1

certificate:
    gateway:
        name: meguurl-gateway-tls
    backend:
        name: kestrel-backend-tls
    caBundle:
        name: local-ca

gatewayClass:
    name: traefik-class
    controllerName: traefik.io/gateway-controller

gateway:
    name: meguurl-gateway
    tlsSecretName: gateway-tls-secret

frontend:
    route:
        name: frontend-route
        hostName: megu.url

    name: meguurl-frontend
    service:
        port: 3000
    deployment:
        port: 3000
    image:
        repo: tomcheese/meguurl-frontend-repo
        tag: k8s
    configmap:
        name: frontend-config
    resources:
        requests:
            cpu: 50m
            memory: 64Mi
        limits:
            cpu: 200m
            memory: 128Mi

backend:
    route:
        name: backend-route
        hostName: api.megu.url

    name: meguurl-backend
    service:
        port: 6767
    deployment:
        port: 6767
    image:
        repo: tomcheese/meguurl-backend-repo
        tag: latest
    configmap:
        name: backend-config
    resources:
        requests:
            cpu: 50m
            memory: 64Mi
        limits:
            cpu: 200m
            memory: 128Mi
    tlsSecretName: meguurl-backend-tls-secret

dbAPI:
    name: meguurl-database-api
    image:
        repo: tomcheese/meguurl-db-api-repo
        tag: latest
    secretName: database-api-secret
    service:
        port: 8000
    deployment:
        port: 8000
    resources:
        requests:
            cpu: 50m
            memory: 64Mi
        limits:
            cpu: 200m
            memory: 128Mi

postgres:
    name: db-postgres
    image:
        repo: postgres
        tag: "18"
    service:
        port: 5432
    statefulSet:
        port: 5432
    secretName: postgres-secret
    persistence:
        name: postgres-storage
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: standard
        size: 10Gi
    requests:
        cpu: 100m
        memory: 256Mi
    limits:
        cpu: 500m
        memory: 512Mi

service:
    type: ClusterIP
    protocol: TCP
    port:
        HTTP: 80
        HTTPS: 443
