certificate:
    gateway: meguurl-gateway-tls

gatewayClass:
    name: traefik-class
    controllerName: traefik.io/gateway-controller

gateway:
    name: meguurl-gateway

frontend:
    route:
        name: frontend-route
        hostName: megu.url
    service:
        name: frontend-service
        port: 80

backend:
    route:
        name: backend-route
        hostName: api.megu.url
    service:
        name: backend-service
        port: 80

testService:
    type: ClusterIP
    port: 80
