apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/issuer: meguurl-local
    name: meguurl-ingress
spec:
    ingressClassName: nginx
    rules:
        - host: meguurl.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: meguurl-frontend
                            port:
                                number: 3000
        - host: api.meguurl.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: meguurl-backend
                            port:
                                number: 6767
    tls:
        - hosts:
              - meguurl.local
              - api.meguurl.local
          secretName: meguurl-local-tls
