apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: {{ .Values.route.name }}
spec:
    parentRefs:
        - name: {{ .Values.gateway.name }}
    hostnames:
        - {{ .Values.route.hostName }}
    rules:
        - matches:
              - path:
                    type: Exact
                    value: /ca.crt
          backendRefs:
              - name: {{ .Values.pod.name }}
                port: 80
