apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.pod.name }}
spec:
    selector:
        app: {{ .Values.pod.name }}
    ports:
        - port: 80
          targetPort: 80
    type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.pod.name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.pod.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.pod.name }}
        spec:
            containers:
                - name: {{ .Values.pod.name }}
                  image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  volumeMounts:
                      - name: ca
                        mountPath: /usr/share/nginx/html/ca.crt
                        subPath: ca.crt
                        readOnly: true
                      
                  resources:
                      {{- toYaml .Values.pod.resources | nindent 20 }}
            volumes:
                - name: ca
                  configMap:
                      name: {{ .Values.ca.bundle.name }}
