kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
    - role: control-plane
      extraPortMappings:
          # HTTP
          - containerPort: 80
            hostPort: 80
            listenAddress: "192.168.2.9"
            protocol: TCP

          # HTTPS
          - containerPort: 443
            hostPort: 443
            listenAddress: "192.168.2.9"
            protocol: TCP

          # DNS - UDP
          - containerPort: 30553
            hostPort: 53
            listenAddress: "192.168.2.2"
            protocol: UDP

          # DNS - TCP
          - containerPort: 30553
            hostPort: 53
            listenAddress: "192.168.2.2"
            protocol: TCP
