apiVersion: v1
kind: ConfigMap
metadata:
    creationTimestamp: "2026-08-16T23:07:15Z"
    name: frontend-config
    namespace: default
    resourceVersion: "4183"
    uid: 3fadd1e1-7954-4c6c-a72c-740f46954b01
data:
    BACKEND: http://meguurl-backend:6767
