apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ .Values.certificate.backend.name}}
spec:
    secretName: {{ .Values.backend.tlsSecretName }}
    issuerRef:
        name: {{ .Values.ca.clusterIssuer.name }}
        kind: ClusterIssuer
    dnsNames:
        - backend
