apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.backend.name }}
    labels:
        app: {{ .Values.backend.name }}

spec:
    selector:
        app: {{ .Values.backend.name }}

    ports:
        - name: "{{ .Values.backend.service.port }}-{{ .Values.backend.deployment.port }}"
          port: {{ .Values.backend.service.port }}
          protocol: {{ .Values.service.protocol }}
          targetPort: {{ .Values.backend.deployment.port }}

    type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.backend.name }}
    labels:
        app: {{ .Values.backend.name }}

spec:
    replicas: {{ .Values.replicaCount }}

    selector:
        matchLabels:
            app: {{ .Values.backend.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.backend.name }}
        spec:
            containers:
                - name: "{{ .Values.backend.name }}-repo"
                  image: "{{ .Values.backend.image.repo }}:{{ .Values.backend.image.tag }}"
                  imagePullPolicy: {{ .Values.imagePullPolicy }}
                  volumeMounts:
                      - name: backend-tls
                        mountPath: /certs
                        readOnly: true
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.backend.configmap.name }}
                  resources:
                      {{- toYaml .Values.backend.resources | nindent 20 }}

            volumes:
                - name: backend-tls
                  secret:
                      secretName: {{ .Values.backend.tlsSecretName }}
