apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.db.api.name }}
    labels:
        app: {{ .Values.db.api.name }}

spec:
    selector:
        app: {{ .Values.db.api.name }}

    ports:
        - name: "{{ .Values.db.api.service.port }}-{{ .Values.db.api.deployment.port }}"
          port: {{ .Values.db.api.service.port }}
          protocol: {{ .Values.service.protocol }}
          targetPort: {{ .Values.db.api.deployment.port }}

    type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.db.api.name }}
    labels:
        app: {{ .Values.db.api.name }}

spec:
    replicas: {{ .Values.replicaCount }}

    selector:
        matchLabels:
            app: {{ .Values.db.api.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.db.api.name }}
        spec:
            containers:
                - name: "{{ .Values.db.api.name }}-repo"
                  image: "{{ .Values.db.api.image.repo }}:{{ .Values.db.api.image.tag }}"
                  imagePullPolicy: {{ .Values.imagePullPolicy }}
                  envFrom:
                      - secretRef:
                            name: {{ .Values.db.api.secretName }}
                  resources: |
                      {{- toYaml .Values.backend.resources | nindent 20 }}
