apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.frontend.name }}
    labels:
        app: {{ .Values.frontend.name }}

spec:
    selector:
        app: {{ .Values.frontend.name }}

    ports:
        - name: "{{ .Values.frontend.service.port }}-{{ .Values.frontend.deployment.port }}"
          port: {{ .Values.frontend.service.port }}
          protocol: {{ .Values.service.protocol }}
          targetPort: {{ .Values.frontend.deployment.port }}

    type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.frontend.name }}
    labels:
        app: {{ .Values.frontend.name }}

spec:
    replicas: {{ .Values.replicaCount }}

    selector:
        matchLabels:
            app: {{ .Values.frontend.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.frontend.name }}
        spec:
            containers:
                - name: "{{ .Values.frontend.name }}-repo"
                  image: "{{ .Values.frontend.image.repo }}:{{ .Values.frontend.image.tag }}"
                  imagePullPolicy: {{ .Values.imagePullPolicy }}
                  volumeMounts:
                      - name: ca-cert
                        mountPath: /certs
                        readOnly: true
                  envFrom:
                      - configMapRef:
                            name: {{ .Values.frontend.configmap.name }}
                  resources: |
                    {{- toYaml .Values.frontend.resources | nindent 20 }}

            volumes:
                - name: ca-cert
                  configMap:
                      name: {{ .Values.certificate.caBundle.name }}
