apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.postgres.name }}
    labels:
        app: {{ .Values.postgres.name }}

spec:
    selector:
        app: {{ .Values.postgres.name }}

    ports:
        - name: "{{ .Values.postgres.service.port }}-{{ .Values.postgres.statefulSet.port }}"
          port: {{ .Values.postgres.service.port }}
          protocol: {{ .Values.service.protocol }}
          targetPort: {{ .Values.postgres.statefulSet.port }}
          
    type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ .Values.postgres.name }}
spec:
    serviceName: {{ .Values.postgres.name }}
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Values.postgres.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.postgres.name }}
        spec:
            containers:
                - name: "{{ .Values.postgres.name }}-repo"
                  image: "{{ .Values.postgres.image.repo }}:{{ .Values.postgres.image.tag }}"
                  imagePullPolicy: {{ .Values.imagePullPolicy }}
                  ports:
                      - containerPort: {{ .Values.postgres.statefulSet.port}}
                        name: {{ .Values.postgres.name }}
                  envFrom:
                      - secretRef:
                            name: {{ .Values.postgres.secretName }}
                  volumeMounts:
                      - name: {{ .Values.postgres.persistence.name }}
                        mountPath: /var/lib/postgresql
                  resources: |
                      {{- toYaml .Values.postgres.resources | nindent 20 }}
    volumeClaimTemplates:
        - metadata:
              name: {{ .Values.postgres.persistence.name }}
          spec:
              accessModes:
                  - {{ .Values.postgres.persistence.accessMode }}
              storageClassName: {{ .Values.postgres.persistence.storageClass }}
              resources:
                  requests:
                      storage: {{ .Values.postgres.persistence.size }}
