gateway:
    name: cert-downloader-gateway

route:
    name: cert-downloader-route
    hostName: cert-downloader.local

image:
    repo: nginx
    tag: alpine
    pullPolicy: IfNotPresent

pod:
    name: cert-downloader
    resources:
        requests:
            memory: 64Mi
            cpu: 100m
        limits:
            memory: 128Mi
            cpu: 200m

service:
    type: ClusterIP
