apiVersion: apps/v1
kind: Deployment
metadata:
    name: meguurl-backend
    labels:
        app: meguurl-backend

spec:
    replicas: 1

    selector:
        matchLabels:
            app: meguurl-backend
    template:
        metadata:
            labels:
                app: meguurl-backend
        spec:
            containers:
                - name: meguurl-backend-repo
                  image: tomcheese/meguurl-backend-repo:latest
                  imagePullPolicy: Always
                  envFrom:
                      - configMapRef:
                            name: backend-config
                  resources: {}
