apiVersion: apps/v1
kind: Deployment
metadata:
    name: meguurl-backend
    labels:
        app: meguurl-backend

spec:
    replicas: 1

    selector:
        matchLabels:
            app: meguurl-backend
    template:
        metadata:
            labels:
                app: meguurl-backend
        spec:
            containers:
                - name: meguurl-backend-repo
                  image: tomcheese/meguurl-backend-repo:latest
                  imagePullPolicy: Always
                  #   image: meguurl-backend:test-v1
                  volumeMounts:
                      - name: backend-tls
                        mountPath: /certs
                        readOnly: true
                  env:
                      - name: NODE_EXTRA_CA_CERTS
                        value: /certs/tls.crt
                  envFrom:
                      - configMapRef:
                            name: backend-config
                  resources: {}

            volumes:
                - name: backend-tls
                  secret:
                      secretName: meguurl-backend-tls
