apiVersion: apps/v1
kind: Deployment
metadata:
    name: meguurl-db-api
    labels:
        app: meguurl-db-api

spec:
    replicas: 1

    selector:
        matchLabels:
            app: meguurl-db-api
    template:
        metadata:
            labels:
                app: meguurl-db-api
        spec:
            containers:
                - name: meguurl-db-api-repo
                  image: tomcheese/meguurl-db-api-repo:latest
                  imagePullPolicy: IfNotPresent
                  envFrom:
                      - secretRef:
                            name: db-api-secrets
                  resources: {}
