apiVersion: apps/v1
kind: Deployment
metadata:
    name: meguurl-frontend
    labels:
        app: meguurl-frontend

spec:
    replicas: 1

    selector:
        matchLabels:
            app: meguurl-frontend
    template:
        metadata:
            labels:
                app: meguurl-frontend
        spec:
            containers:
                - name: meguurl-frontend-repo
                  image: tomcheese/meguurl-frontend-repo:k8s
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: ca-cert
                        mountPath: /certs
                        readOnly: true
                  envFrom:
                      - configMapRef:
                            name: frontend-config
                  resources: {}

            volumes:
                - name: ca-cert
                  secret:
                      secretName: meguurl-local-ca
