apiVersion: v1
kind: Service
metadata:
    name: meguurl-backend
    labels:
        app: meguurl-backend

spec:
    selector:
        app: meguurl-backend

    ports:
        - name: 6767-6767
          port: 6767
          protocol: TCP
          targetPort: 6767

    type: ClusterIP
