apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-08-16T22:47:28Z"
  labels:
    app: meguurl-backend
  name: meguurl-backend
  namespace: default
  resourceVersion: "2135"
  uid: 9ec4df63-172a-4edd-9e5c-cff0d02c63de
spec:
  clusterIP: 10.96.158.124
  clusterIPs:
  - 10.96.158.124
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 6767-8080
    port: 6767
    protocol: TCP
    targetPort: 8080
  selector:
    app: meguurl-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
