apiVersion: v1
kind: Service
metadata:
    name: meguurl-backend
    labels:
        app: meguurl-backend

spec:
    selector:
        app: meguurl-backend

    ports:
        - name: 6767-8080
          port: 6767
          protocol: TCP
          targetPort: 8080
          
    type: ClusterIP
