apiVersion: v1
kind: Service
metadata:
    name: meguurl-db-api
    labels:
        app: meguurl-db-api

spec:
    selector:
        app: meguurl-db-api

    ports:
        - name: 8000-8000
          port: 8000
          protocol: TCP
          targetPort: 8000
          
    type: ClusterIP
