apiVersion: v1
kind: Service
metadata:
    name: meguurl-frontend
    labels:
        app: meguurl-frontend

spec:
    selector:
        app: meguurl-frontend

    ports:
        - name: 3000-3000
          port: 3000
          protocol: TCP
          targetPort: 3000

    type: ClusterIP
