apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.backend.configmap.name }}
data:
    ApiSettings__BackendApi: https://{{ .Values.backend.name }}:{{ .Values.backend.service.port }}/
    ApiSettings__DatabaseApi: http://{{ .Values.dbAPI.name }}:{{ .Values.dbAPI.service.port }}/
    ASPNETCORE_USE_K8S_TLS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.frontend.configmap.name }}
data:
    BACKEND: https://{{ .Values.backend.name }}:{{ .Values.backend.service.port }}
    NODE_EXTRA_CA_CERTS: /certs/ca.crt
