apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
    name: "{{ .Values.backend.name }}-tls"

spec:
    targetRefs:
        - group: ""
          kind: Service
          name: {{ .Values.backend.name }}

    validation:
        hostname: "{{ .Values.backend.name }}.{{ .Release.Namespace }}.svc.cluster.local"
        caCertificateRefs:
            - group: ""
              kind: ConfigMap
              name: {{ .Values.certificate.caBundle.name }}
